export const PerformanceData = [
  {
    model: 1,
    metrics: {
      data: [
        {
          metric: "f1",
          everyone: 0.601,
          nobody: 0.958,
          x: 0.941,
          o: 0.916,
          average: 0.854,
          w_average: 0.94,
        },
        {
          metric: "Precision",
          everyone: 0.774,
          nobody: 0.931,
          x: 0.959,
          o: 0.965,
          average: 0.907,
          w_average: 0.942,
        },
        {
          metric: "Recall",
          everyone: 0.491,
          nobody: 0.987,
          x: 0.923,
          o: 0.872,
          average: 0.818,
          w_average: 0.942,
        },
      ],
      columns: [
        { property: "metric", primary: true },
        { property: "everyone", header: "Everyone" },
        { property: "nobody", header: "Nobody" },
        { property: "x", header: "X" },
        { property: "o", header: "O" },
        { property: "average", header: "Average" },
        { property: "w_average", header: "Weighted Average" },
      ],
    },
    confusion_matrix: {
      data: [
        {
          predicted: "Everyone",
          true_everyone: 113,
          true_nobody: 0,
          true_x: 18,
          true_o: 15,
        },
        {
          predicted: "Nobody",
          true_everyone: 2,
          true_nobody: 8203,
          true_x: 222,
          true_o: 380,
        },
        {
          predicted: "X",
          true_everyone: 75,
          true_nobody: 48,
          true_x: 2886,
          true_o: 1,
        },
        {
          predicted: "O",
          true_everyone: 40,
          true_nobody: 59,
          true_x: 0,
          true_o: 2701,
        },
      ],
      columns: [
        { property: "predicted", primary: true },
        { property: "true_everyone", header: "Everyone" },
        { property: "true_nobody", header: "Nobody" },
        { property: "true_x", header: "X" },
        { property: "true_o", header: "O" },
      ],
    },
  },
  {
    model: 2,
    metrics: {
      data: [
        {
          metric: "f1",
          everyone: 0.621,
          nobody: 0.977,
          x: 0.951,
          o: 0.96,
          average: 0.877,
          w_average: 0.962,
        },
        {
          metric: "Precision",
          everyone: 0.832,
          nobody: 0.963,
          x: 0.96,
          o: 0.972,
          average: 0.932,
          w_average: 0.963,
        },
        {
          metric: "Recall",
          everyone: 0.496,
          nobody: 0.99,
          x: 0.943,
          o: 0.948,
          average: 0.844,
          w_average: 0.963,
        },
      ],
      columns: [
        { property: "metric", primary: true },
        { property: "everyone", header: "Everyone" },
        { property: "nobody", header: "Nobody" },
        { property: "x", header: "X" },
        { property: "o", header: "O" },
        { property: "average", header: "Average" },
        { property: "w_average", header: "Weighted Average" },
      ],
    },
    confusion_matrix: {
      data: [
        {
          predicted: "Everyone",
          true_everyone: 114,
          true_nobody: 0,
          true_x: 11,
          true_o: 12,
        },
        {
          predicted: "Nobody",
          true_everyone: 1,
          true_nobody: 8227,
          true_x: 166,
          true_o: 145,
        },
        {
          predicted: "X",
          true_everyone: 63,
          true_nobody: 54,
          true_x: 2947,
          true_o: 5,
        },
        {
          predicted: "O",
          true_everyone: 52,
          true_nobody: 29,
          true_x: 2,
          true_o: 2935,
        },
      ],
      columns: [
        { property: "predicted", primary: true },
        { property: "true_everyone", header: "Everyone" },
        { property: "true_nobody", header: "Nobody" },
        { property: "true_x", header: "X" },
        { property: "true_o", header: "O" },
      ],
    },
  },
  {
    model: 3,
    metrics: {
      data: [
        {
          metric: "f1",
          everyone: 0.198,
          nobody: 0.73,
          x: 0.638,
          o: 0.62,
          average: 0.547,
          w_average: 0.679,
        },
        {
          metric: "Precision",
          everyone: 0.111,
          nobody: 0.841,
          x: 0.594,
          o: 0.642,
          average: 0.547,
          w_average: 0.736,
        },
        {
          metric: "Recall",
          everyone: 0.904,
          nobody: 0.646,
          x: 0.688,
          o: 0.6,
          average: 0.709,
          w_average: 0.649,
        },
      ],
      columns: [
        { property: "metric", primary: true },
        { property: "everyone", header: "Everyone" },
        { property: "nobody", header: "Nobody" },
        { property: "x", header: "X" },
        { property: "o", header: "O" },
        { property: "average", header: "Average" },
        { property: "w_average", header: "Weighted Average" },
      ],
    },
    confusion_matrix: {
      data: [
        {
          predicted: "Everyone",
          true_everyone: 208,
          true_nobody: 499,
          true_x: 494,
          true_o: 666,
        },
        {
          predicted: "Nobody",
          true_everyone: 6,
          true_nobody: 499,
          true_x: 472,
          true_o: 540,
        },
        {
          predicted: "X",
          true_everyone: 12,
          true_nobody: 1423,
          true_x: 2150,
          true_o: 33,
        },
        {
          predicted: "O",
          true_everyone: 4,
          true_nobody: 1023,
          true_x: 10,
          true_o: 1858,
        },
      ],
      columns: [
        { property: "predicted", primary: true },
        { property: "true_everyone", header: "Everyone" },
        { property: "true_nobody", header: "Nobody" },
        { property: "true_x", header: "X" },
        { property: "true_o", header: "O" },
      ],
    },
  },
  {
    model: 4,
    metrics: {
      data: [
        {
          metric: "f1",
          everyone: 0.737,
          nobody: 0.977,
          x: 0.956,
          o: 0.963,
          average: 0.908,
          w_average: 0.966,
        },
        {
          metric: "Precision",
          everyone: 0.784,
          nobody: 0.97,
          x: 0.963,
          o: 0.97,
          average: 0.922,
          w_average: 0.966,
        },
        {
          metric: "Recall",
          everyone: 0.696,
          nobody: 0.984,
          x: 0.949,
          o: 0.956,
          average: 0.896,
          w_average: 0.966,
        },
      ],
      columns: [
        { property: "metric", primary: true },
        { property: "everyone", header: "Everyone" },
        { property: "nobody", header: "Nobody" },
        { property: "x", header: "X" },
        { property: "o", header: "O" },
        { property: "average", header: "Average" },
        { property: "w_average", header: "Weighted Average" },
      ],
    },
    confusion_matrix: {
      data: [
        {
          predicted: "Everyone",
          true_everyone: 160,
          true_nobody: 2,
          true_x: 16,
          true_o: 26,
        },
        {
          predicted: "Nobody",
          true_everyone: 2,
          true_nobody: 8174,
          true_x: 141,
          true_o: 109,
        },
        {
          predicted: "X",
          true_everyone: 25,
          true_nobody: 85,
          true_x: 2968,
          true_o: 2,
        },
        {
          predicted: "O",
          true_everyone: 43,
          true_nobody: 49,
          true_x: 1,
          true_o: 2960,
        },
      ],
      columns: [
        { property: "predicted", primary: true },
        { property: "true_everyone", header: "Everyone" },
        { property: "true_nobody", header: "Nobody" },
        { property: "true_x", header: "X" },
        { property: "true_o", header: "O" },
      ],
    },
  },
  {
    model: 5,
    metrics: {
      data: [
        {
          metric: "f1",
          everyone: 0.331,
          nobody: 0.934,
          x: 0.898,
          o: 0.874,
          average: 0.759,
          w_average: 0.905,
        },
        {
          metric: "Precision",
          everyone: 0.455,
          nobody: 0.905,
          x: 0.936,
          o: 0.905,
          average: 0.8,
          w_average: 0.905,
        },
        {
          metric: "Recall",
          everyone: 0.261,
          nobody: 0.965,
          x: 0.862,
          o: 0.846,
          average: 0.734,
          w_average: 0.907,
        },
      ],
      columns: [
        { property: "metric", primary: true },
        { property: "everyone", header: "Everyone" },
        { property: "nobody", header: "Nobody" },
        { property: "x", header: "X" },
        { property: "o", header: "O" },
        { property: "average", header: "Average" },
        { property: "w_average", header: "Weighted Average" },
      ],
    },
    confusion_matrix: {
      data: [
        {
          predicted: "Everyone",
          true_everyone: 60,
          true_nobody: 2,
          true_x: 39,
          true_o: 31,
        },
        {
          predicted: "Nobody",
          true_everyone: 7,
          true_nobody: 8020,
          true_x: 387,
          true_o: 443,
        },
        {
          predicted: "X",
          true_everyone: 80,
          true_nobody: 101,
          true_x: 2696,
          true_o: 4,
        },
        {
          predicted: "O",
          true_everyone: 83,
          true_nobody: 187,
          true_x: 4,
          true_o: 2619,
        },
      ],
      columns: [
        { property: "predicted", primary: true },
        { property: "true_everyone", header: "Everyone" },
        { property: "true_nobody", header: "Nobody" },
        { property: "true_x", header: "X" },
        { property: "true_o", header: "O" },
      ],
    },
  },
  {
    model: 6,
    metrics: {
      data: [
        {
          metric: "f1",
          everyone: 0.764,
          nobody: 0.942,
          x: 0.914,
          o: 0.91,
          average: 0.882,
          w_average: 0.927,
        },
        {
          metric: "Precision",
          everyone: 0.702,
          nobody: 0.966,
          x: 0.89,
          o: 0.884,
          average: 0.861,
          w_average: 0.929,
        },
        {
          metric: "Recall",
          everyone: 0.839,
          nobody: 0.92,
          x: 0.939,
          o: 0.936,
          average: 0.908,
          w_average: 0.926,
        },
      ],
      columns: [
        { property: "metric", primary: true },
        { property: "everyone", header: "Everyone" },
        { property: "nobody", header: "Nobody" },
        { property: "x", header: "X" },
        { property: "o", header: "O" },
        { property: "average", header: "Average" },
        { property: "w_average", header: "Weighted Average" },
      ],
    },
    confusion_matrix: {
      data: [
        {
          predicted: "Everyone",
          true_everyone: 193,
          true_nobody: 0,
          true_x: 37,
          true_o: 45,
        },
        {
          predicted: "Nobody",
          true_everyone: 0,
          true_nobody: 7642,
          true_x: 131,
          true_o: 139,
        },
        {
          predicted: "X",
          true_everyone: 20,
          true_nobody: 330,
          true_x: 2934,
          true_o: 13,
        },
        {
          predicted: "O",
          true_everyone: 17,
          true_nobody: 338,
          true_x: 24,
          true_o: 2900,
        },
      ],
      columns: [
        { property: "predicted", primary: true },
        { property: "true_everyone", header: "Everyone" },
        { property: "true_nobody", header: "Nobody" },
        { property: "true_x", header: "X" },
        { property: "true_o", header: "O" },
      ],
    },
  },
  {
    model: 7,
    metrics: {
      data: [
        {
          metric: "f1",
          everyone: 0.759,
          nobody: 0.984,
          x: 0.969,
          o: 0.969,
          average: 0.92,
          w_average: 0.974,
        },
        {
          metric: "Precision",
          everyone: 0.682,
          nobody: 0.994,
          x: 0.964,
          o: 0.959,
          average: 0.9,
          w_average: 0.975,
        },
        {
          metric: "Recall",
          everyone: 0.857,
          nobody: 0.975,
          x: 0.974,
          o: 0.978,
          average: 0.946,
          w_average: 0.974,
        },
      ],
      columns: [
        { property: "metric", primary: true },
        { property: "everyone", header: "Everyone" },
        { property: "nobody", header: "Nobody" },
        { property: "x", header: "X" },
        { property: "o", header: "O" },
        { property: "average", header: "Average" },
        { property: "w_average", header: "Weighted Average" },
      ],
    },
    confusion_matrix: {
      data: [
        {
          predicted: "Everyone",
          true_everyone: 197,
          true_nobody: 0,
          true_x: 48,
          true_o: 44,
        },
        {
          predicted: "Nobody",
          true_everyone: 0,
          true_nobody: 8103,
          true_x: 30,
          true_o: 22,
        },
        {
          predicted: "X",
          true_everyone: 11,
          true_nobody: 102,
          true_x: 3046,
          true_o: 2,
        },
        {
          predicted: "O",
          true_everyone: 22,
          true_nobody: 105,
          true_x: 2,
          true_o: 3029,
        },
      ],
      columns: [
        { property: "predicted", primary: true },
        { property: "true_everyone", header: "Everyone" },
        { property: "true_nobody", header: "Nobody" },
        { property: "true_x", header: "X" },
        { property: "true_o", header: "O" },
      ],
    },
  },
];
